"""Add project and consensus analysis models

Revision ID: 9e408895f93a
Revises: 20260120_exports
Create Date: 2026-01-27 07:15:07.496366

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e408895f93a'
down_revision: str | None = '20260120_exports'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'READY', 'ANALYZING', 'ANALYZED', 'FAILED', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('consensus_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('arq_job_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'CONVERGED', 'FAILED', 'CANCELLED', name='analysisstatus'), nullable=False),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.Column('convergence_reason', sa.String(length=100), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('final_confidence', sa.Float(), nullable=True),
    sa.Column('final_novelty', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('milestones_count', sa.Integer(), nullable=False),
    sa.Column('checkpoints_count', sa.Integer(), nullable=False),
    sa.Column('versions_count', sa.Integer(), nullable=False),
    sa.Column('consensus_rounds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consensus_analyses_arq_job_id'), 'consensus_analyses', ['arq_job_id'], unique=True)
    op.create_index(op.f('ix_consensus_analyses_created_at'), 'consensus_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_consensus_analyses_id'), 'consensus_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_consensus_analyses_project_id'), 'consensus_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_consensus_analyses_status'), 'consensus_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_consensus_analyses_user_id'), 'consensus_analyses', ['user_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'document_id')
    )
    op.create_table('milestones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('TECHNICAL', 'PRODUCT', 'HYBRID', name='milestonetype'), nullable=False),
    sa.Column('estimated_effort', sa.Enum('S', 'M', 'L', 'XL', name='effortsize'), nullable=False),
    sa.Column('dependencies', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['consensus_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_analysis_id'), 'milestones', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_type'), 'milestones', ['type'], unique=False)
    op.create_table('versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('release_goal', sa.Text(), nullable=False),
    sa.Column('milestone_titles', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['consensus_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versions_analysis_id'), 'versions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_versions_id'), 'versions', ['id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('milestone_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('POC', 'DEMO', 'TEST', 'REVIEW', name='checkpointtype'), nullable=False),
    sa.Column('validation_criteria', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['consensus_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_analysis_id'), 'checkpoints', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_id'), 'checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_checkpoints_milestone_id'), 'checkpoints', ['milestone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkpoints_milestone_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_analysis_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_versions_id'), table_name='versions')
    op.drop_index(op.f('ix_versions_analysis_id'), table_name='versions')
    op.drop_table('versions')
    op.drop_index(op.f('ix_milestones_type'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_milestones_analysis_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_consensus_analyses_user_id'), table_name='consensus_analyses')
    op.drop_index(op.f('ix_consensus_analyses_status'), table_name='consensus_analyses')
    op.drop_index(op.f('ix_consensus_analyses_project_id'), table_name='consensus_analyses')
    op.drop_index(op.f('ix_consensus_analyses_id'), table_name='consensus_analyses')
    op.drop_index(op.f('ix_consensus_analyses_created_at'), table_name='consensus_analyses')
    op.drop_index(op.f('ix_consensus_analyses_arq_job_id'), table_name='consensus_analyses')
    op.drop_table('consensus_analyses')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
