"""fix documents user_id type

Revision ID: 0c9ce5097329
Revises: 75b5025fadd6
Create Date: 2026-01-09 11:32:08.462348

"""
from collections.abc import Sequence
from typing import Union

# revision identifiers, used by Alembic.
revision: str = '0c9ce5097329'
down_revision: Union[str, None] = '75b5025fadd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
