"""add document processing fields and generation job relationship

Revision ID: 7a66a7d54df2
Revises: 0c9ce5097329
Create Date: 2026-01-13 19:25:54.886290

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a66a7d54df2"
down_revision: Union[str, None] = "0c9ce5097329"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    documentstatus = sa.Enum("UPLOADED", "PROCESSING", "PROCESSED", "FAILED", name="documentstatus")
    documentstatus.create(op.get_bind())

    # Add column as nullable first, populate with default, then make non-nullable
    op.add_column("documents", sa.Column("status", documentstatus, nullable=True))
    op.execute("UPDATE documents SET status = 'UPLOADED' WHERE status IS NULL")
    op.alter_column("documents", "status", nullable=False)
    op.add_column("documents", sa.Column("content_hash", sa.String(length=64), nullable=True))
    op.add_column(
        "documents",
        sa.Column("processed_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column("documents", sa.Column("processing_error", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_documents_content_hash"), "documents", ["content_hash"], unique=False)
    op.create_index(op.f("ix_documents_status"), "documents", ["status"], unique=False)
    op.add_column("generation_jobs", sa.Column("document_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_generation_jobs_document_id"), "generation_jobs", ["document_id"], unique=False
    )
    op.create_foreign_key(
        None, "generation_jobs", "documents", ["document_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "generation_jobs", type_="foreignkey")
    op.drop_index(op.f("ix_generation_jobs_document_id"), table_name="generation_jobs")
    op.drop_column("generation_jobs", "document_id")
    op.drop_index(op.f("ix_documents_status"), table_name="documents")
    op.drop_index(op.f("ix_documents_content_hash"), table_name="documents")
    op.drop_column("documents", "processed_at")
    op.drop_column("documents", "processing_error")
    op.drop_column("documents", "processed_content")
    op.drop_column("documents", "content_hash")
    op.drop_column("documents", "status")
    documentstatus = sa.Enum("UPLOADED", "PROCESSING", "PROCESSED", "FAILED", name="documentstatus")
    documentstatus.drop(op.get_bind())
    # ### end Alembic commands ###
